"use client";

import { useMemo, useState } from "react";
import { report } from "./report-data";

type Stock = (typeof report.themes)[number]["stocks"][number];
type Tier = Stock["tier"];
type ExitedStock = { code: string; name: string; previous_tier: string; theme: string | null; reason: string };
const fugleUrl = (code: string) => `https://www.fugle.tw/ai/${code}`;
const isNewStock = (stock: unknown) => Boolean((stock as { is_new?: boolean }).is_new);
const stockIsActive = (stock: unknown) => (stock as { is_active?: boolean }).is_active !== false;
const stockStateLabel = (stock: unknown) => {
  const state = stock as { is_active?: boolean; lifecycle_status?: string; miss_streak?: number; previous_tier?: string; tier?: string; tier_change?: string };
  if (state.is_active === false) return `${state.lifecycle_status} ${state.miss_streak}/2`;
  if (state.tier_change === "up" || state.tier_change === "down") return `${state.previous_tier}→${state.tier} ${state.tier_change === "up" ? "升級" : "降級"}`;
  if (state.tier_change === "returning") return "回溫";
  return null;
};
const themeLifecycle = (theme: unknown) => (theme as { lifecycle?: string }).lifecycle ?? "成熟";
const lifecycleClass = (value: string) => ({ 啟動: "launch", 擴散: "expand", 成熟: "mature", 退潮: "cooling" }[value] ?? "mature");
const tierCopy: Record<Tier, string> = { S: "長短週期均強勢", A: "動能具延續性", B: "值得持續追蹤", C: "早期群聚訊號" };

export default function Home() {
  const [tier, setTier] = useState<"all" | Tier>("all");
  const [query, setQuery] = useState("");
  const visibleThemes = useMemo(() => report.themes.map((theme) => ({ ...theme, stocks: theme.stocks.filter((stock) => (tier === "all" || stock.tier === tier) && `${stock.code}${stock.name}${theme.name}`.toLowerCase().includes(query.toLowerCase())) })).filter((theme) => theme.stocks.length), [query, tier]);
  const stockCount = visibleThemes.reduce((sum, theme) => sum + theme.stocks.length, 0);
  const exitedStocks = ((report as unknown) as { exited_stocks?: ExitedStock[] }).exited_stocks ?? [];
  const date = new Date(report.generated_at).toLocaleDateString("zh-TW", { month: "long", day: "numeric" });

  return <main>
    <header className="topbar"><a className="wordmark" href="#top" aria-label="台股題材雷達首頁"><span className="wordmark-mark"><i /><i /><i /></span><span>THEME<br /><b>ATLAS</b></span></a><div className="topbar-center">TAIWAN EQUITY / CAPITAL FLOW OBSERVATORY</div><div className="refresh"><span />資料更新 {date}</div></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">THEME ATLAS / 2026</p><h1>先看見<span>群聚</span><br />再追蹤個股。</h1><p className="hero-lead">把七個漲幅時間窗疊成一張資金地圖：反覆出現的強勢股形成核心；近期才一起出現的同族群，則標示為值得觀察的早期訊號。</p><div className="hero-actions"><a href="#report" className="button-primary">探索今日題材 <b>↓</b></a><span>非投資建議<br />僅供研究追蹤</span></div><div className="headline-stats"><div><b>{report.themes.length}</b><span>個題材群聚</span></div><div><b>{stockCount}</b><span>檔可追蹤標的</span></div><div><b>7</b><span>組觀察週期</span></div></div></div>
      <div className="atlas-visual" aria-label="題材群聚與資金流向示意圖"><img src="/theme-atlas-hero.png" alt="抽象題材群聚與資金流向地圖" /><div className="orbit orbit-one" /><div className="orbit orbit-two" />{report.themes.slice(0, 3).map((theme, index) => <div className={`theme-pin pin-${index + 1}`} key={theme.name}><span>THEME {theme.tier}</span><b>{theme.name}</b><em>{theme.score} pts</em></div>)}<div className="visual-caption"><i /> 資金動能流向<br /><span>CORE ↔ EMERGING</span></div></div></section>
    <section className="timeline" aria-label="分析時間區間"><p><span>SCAN RANGE</span> 由近期到中期，判讀動能是否擴散</p><div>{["1d", "2d", "3d", "4d", "5d", "10d", "20d"].map((window, index) => <span className={index < 3 ? "recent" : ""} key={window}>{window}</span>)}</div><small>近期加權、連續性與榜單百分位共同判讀</small></section>
    <section className="content" id="report"><aside className="reading-guide"><div className="guide-intro"><p className="eyebrow">HOW TO READ</p><h2>把「新」與「強」放在同一張圖裡。</h2></div><div className="guide-steps"><div className="guide-step"><b>01</b><p><strong>核心群聚</strong>以近期加權、榜單百分位與連續出現格數，辨識可持續的強勢。</p></div><div className="guide-step"><b>02</b><p><strong>早期群聚</strong>近期高名次標的須跨至少兩個近端視窗，且同題材成群出現，才保留為 C Tier。</p></div><div className="guide-step"><b>03</b><p><strong>題材排序</strong>以最強三檔的核心動能為主，再加入群聚廣度。</p></div><div className="guide-step"><b>04</b><p><strong>退潮汰換</strong>連續兩次未達標仍保留觀察，第 3 次才退出並通知。</p></div></div><div className="tier-key"><span><b className="dot s">S</b> 核心強勢</span><span><b className="dot a">A</b> 延續動能</span><span><b className="dot b">B</b> 持續觀察</span><span><b className="dot c">C</b> 早期群聚</span></div></aside>
      <section className="report-panel"><header className="panel-header"><div><p className="eyebrow">LIVE THEME CLUSTERS</p><h2>今日資金流向圖譜</h2></div><p>同義產品與上下游關係會合併至同一標準題材；點選個股可前往 Fugle</p></header><div className="controls"><div className="tier-filter" aria-label="篩選標的 Tier">{(["all", "S", "A", "B", "C"] as const).map((value) => <button key={value} className={tier === value ? "selected" : ""} onClick={() => setTier(value)}>{value === "all" ? "全部訊號" : `Tier ${value}`}</button>)}</div><label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋代號、標的或題材" /></label></div><div className="theme-grid">{visibleThemes.map((theme, index) => <article className={`theme-card theme-card-${index % 3}`} key={theme.name}><header><div className="cluster-symbol"><i /><i /><i /><i /></div><div><p>可能性題材 / TIER {theme.tier}{theme.provisional_count > 0 ? ` · 含 ${theme.provisional_count} 檔疑似` : ""}</p><h3>{theme.name}<em className={`lifecycle-chip ${lifecycleClass(themeLifecycle(theme))}`}>{themeLifecycle(theme)}</em></h3></div><div className="score"><span>核心 {theme.core_strength}</span><b>{theme.score}</b><small>pts</small></div></header><div className="cluster-line"><span style={{ width: `${Math.min(100, 25 + theme.score * 2)}%` }} /></div><div className="stock-list">{theme.stocks.map((stock) => <a href={fugleUrl(stock.code)} target="_blank" rel="noreferrer" className={`stock${stock.is_provisional ? " provisional" : ""}${!stockIsActive(stock) ? " cooling-stock" : ""}`} key={stock.code} aria-label={`前往 Fugle 查看 ${stock.code} ${stock.name}`}><span className={`stock-badge tier-${stock.tier}`}>{stock.tier}</span><span className="stock-name"><b>{stock.name}{isNewStock(stock) && <em className="new-tag">NEW</em>}{stockStateLabel(stock) && <em className="state-tag">{stockStateLabel(stock)}</em>}{stock.is_provisional && <em>疑似</em>}</b><small>{stock.code} · {stock.product_label ?? tierCopy[stock.tier]}{stock.theme_basis === "產品面推論" ? " · 待覆核" : ""}</small></span><span className="stock-windows">{stock.windows.map((window) => <i key={window}>{window}</i>)}</span><span className="stock-meta"><b>動能 {stock.signal_score}</b><small>{stockStateLabel(stock) ?? `連續 ${stock.continuity} 格`}</small></span><span className="arrow">↗</span></a>)}</div></article>)}</div>{!visibleThemes.length && <div className="empty">沒有符合目前篩選條件的題材或標的。</div>}</section></section>
    {report.unmapped_candidates.length > 0 && <section className="inference-desk"><div className="inference-head"><div><p className="eyebrow">INFERENCE DESK</p><h2>尚無題材假說</h2><p>已有產品／題材假說的候選會以「疑似」身份直接加入上方題材；此處只保留尚缺研究資料、暫時無法歸納的標的。</p></div><b>{report.unmapped_candidates.length} 檔<br /><small>P1 {report.review_summary.required} · 已研究 {report.review_summary.reviewed}</small></b></div><div className="candidate-grid">{report.unmapped_candidates.map((stock) => <a href={fugleUrl(stock.code)} target="_blank" rel="noreferrer" className={`candidate${!stockIsActive(stock) ? " cooling-stock" : ""}`} key={stock.code}><span className={`stock-badge tier-${stock.tier}`}>{stock.tier}</span><span><b>{stock.name}{isNewStock(stock) && <em className="new-tag">NEW</em>}{stockStateLabel(stock) && <em className="state-tag">{stockStateLabel(stock)}</em>}</b><small>{stock.code} · {stock.review_priority} · {stock.review_status}</small></span><span className="candidate-windows" aria-label={`${stock.name} 上榜時間窗`}>{stock.windows.map((window) => <i key={window}>{window}</i>)}</span><span><b>動能 {stock.signal_score}</b><small>{stock.appearances}x · 連續 {stock.continuity} 格</small></span><i>↗</i></a>)}</div></section>}
    {exitedStocks.length > 0 && <section className="exit-desk"><div><p className="eyebrow">DAILY ROTATION</p><h2>今日正式汰換</h2><p>連續第 3 次未達標的 Tier 或群聚條件，退出當日圖譜；歷史與題材 Mapping 仍保留。</p></div><div className="exit-grid">{exitedStocks.map((stock) => <a href={fugleUrl(stock.code)} target="_blank" rel="noreferrer" className="exit-stock" key={stock.code}><span><b>{stock.name}</b><small>{stock.code} · 前 Tier {stock.previous_tier} · {stock.theme ?? "尚無題材"}</small></span><em>已汰換</em><i>↗</i></a>)}</div></section>}
    <footer><span>THEME ATLAS — 將多週期排行轉譯為題材群聚脈絡</span><span>資料來源：富邦證券台股進階數據</span></footer>
  </main>;
}
