// Generated by analyze_twse_momentum.py. Do not edit manually.
export const report = {
  "generated_at": "2026-08-09T00:57:32.421550+08:00",
  "freshness": "fresh",
  "last_error": null,
  "source_urls": {
    "1d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_1.djhtm",
    "2d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_2.djhtm",
    "3d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_3.djhtm",
    "4d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_4.djhtm",
    "5d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_5.djhtm",
    "10d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_10.djhtm",
    "20d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_20.djhtm"
  },
  "themes": [
    {
      "name": "AI 基礎建設 / 高速傳輸",
      "score": 60,
      "core_strength": 14.44,
      "breadth": 5,
      "early_cluster_count": 0,
      "mapping_basis": [
        "人工題材對照"
      ],
      "stocks": [
        {
          "code": "6426",
          "name": "統新",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 6,
          "effective_appearances": 5.15,
          "continuity": 6,
          "avg_rank": 6.2,
          "avg_rank_percentile": 10.7,
          "signal_score": 5.37,
          "avg_gain_pct": 23.44,
          "latest_window": "1d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "S"
        },
        {
          "code": "6213",
          "name": "聯茂",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 5,
          "effective_appearances": 4.15,
          "continuity": 5,
          "avg_rank": 3.4,
          "avg_rank_percentile": 5.0,
          "signal_score": 4.57,
          "avg_gain_pct": 29.55,
          "latest_window": "2d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "S"
        },
        {
          "code": "7711",
          "name": "永擎",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 6,
          "effective_appearances": 4.65,
          "continuity": 6,
          "avg_rank": 9.8,
          "avg_rank_percentile": 18.2,
          "signal_score": 4.5,
          "avg_gain_pct": 23.9,
          "latest_window": "2d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "S"
        },
        {
          "code": "6269",
          "name": "台郡",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 5,
          "effective_appearances": 4.15,
          "continuity": 5,
          "avg_rank": 16.4,
          "avg_rank_percentile": 31.8,
          "signal_score": 3.45,
          "avg_gain_pct": 21.56,
          "latest_window": "2d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "A"
        },
        {
          "code": "3653",
          "name": "健策",
          "windows": [
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 4,
          "effective_appearances": 2.8,
          "continuity": 4,
          "avg_rank": 15.5,
          "avg_rank_percentile": 29.6,
          "signal_score": 2.39,
          "avg_gain_pct": 27.13,
          "latest_window": "4d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "A"
        }
      ],
      "tier": 1
    },
    {
      "name": "機器人 / 智慧製造",
      "score": 44,
      "core_strength": 10.57,
      "breadth": 4,
      "early_cluster_count": 0,
      "mapping_basis": [
        "人工題材對照"
      ],
      "stocks": [
        {
          "code": "4540",
          "name": "全球傳動",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 6,
          "effective_appearances": 5.15,
          "continuity": 6,
          "avg_rank": 13.0,
          "avg_rank_percentile": 24.9,
          "signal_score": 4.64,
          "avg_gain_pct": 18.88,
          "latest_window": "1d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "S"
        },
        {
          "code": "2049",
          "name": "上銀",
          "windows": [
            "1d",
            "3d",
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 6,
          "effective_appearances": 4.7,
          "continuity": 5,
          "avg_rank": 22.8,
          "avg_rank_percentile": 45.2,
          "signal_score": 3.14,
          "avg_gain_pct": 17.92,
          "latest_window": "1d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "B"
        },
        {
          "code": "3167",
          "name": "大量",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 4,
          "effective_appearances": 3.5,
          "continuity": 4,
          "avg_rank": 18.0,
          "avg_rank_percentile": 35.2,
          "signal_score": 2.79,
          "avg_gain_pct": 24.11,
          "latest_window": "2d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "A"
        },
        {
          "code": "2464",
          "name": "盟立",
          "windows": [
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 3,
          "effective_appearances": 2.3,
          "continuity": 3,
          "avg_rank": 19.3,
          "avg_rank_percentile": 37.6,
          "signal_score": 1.78,
          "avg_gain_pct": 21.69,
          "latest_window": "4d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "A"
        }
      ],
      "tier": 2
    },
    {
      "name": "記憶體 / IC 設計",
      "score": 38,
      "core_strength": 9.05,
      "breadth": 3,
      "early_cluster_count": 0,
      "mapping_basis": [
        "人工題材對照"
      ],
      "stocks": [
        {
          "code": "6531",
          "name": "愛普*",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 5,
          "effective_appearances": 4.5,
          "continuity": 5,
          "avg_rank": 13.0,
          "avg_rank_percentile": 25.2,
          "signal_score": 4.04,
          "avg_gain_pct": 21.44,
          "latest_window": "1d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "S"
        },
        {
          "code": "3006",
          "name": "晶豪科",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 5,
          "effective_appearances": 4.15,
          "continuity": 5,
          "avg_rank": 15.0,
          "avg_rank_percentile": 29.0,
          "signal_score": 3.57,
          "avg_gain_pct": 24.36,
          "latest_window": "2d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "S"
        },
        {
          "code": "4967",
          "name": "十銓",
          "windows": [
            "4d",
            "10d",
            "20d"
          ],
          "appearances": 3,
          "effective_appearances": 2.0,
          "continuity": 2,
          "avg_rank": 18.7,
          "avg_rank_percentile": 36.4,
          "signal_score": 1.44,
          "avg_gain_pct": 21.66,
          "latest_window": "4d",
          "theme_basis": "人工題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "tier": "B"
        }
      ],
      "tier": 3
    },
    {
      "name": "伺服器導軌 / 機櫃滑軌",
      "score": 24,
      "core_strength": 6.0,
      "breadth": 1,
      "early_cluster_count": 0,
      "mapping_basis": [
        "產品面推論"
      ],
      "stocks": [
        {
          "code": "2059",
          "name": "川湖",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 7,
          "effective_appearances": 5.65,
          "continuity": 7,
          "avg_rank": 5.3,
          "avg_rank_percentile": 8.8,
          "signal_score": 6.0,
          "avg_gain_pct": 27.55,
          "latest_window": "1d",
          "theme_basis": "產品面推論",
          "theme_confidence": "待覆核",
          "product_label": "伺服器導軌、機櫃滑軌",
          "tier": "S"
        }
      ],
      "tier": 4
    },
    {
      "name": "軟板材料 / FCCL",
      "score": 18,
      "core_strength": 4.47,
      "breadth": 1,
      "early_cluster_count": 0,
      "mapping_basis": [
        "產品面推論"
      ],
      "stocks": [
        {
          "code": "8039",
          "name": "台虹",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "20d"
          ],
          "appearances": 6,
          "effective_appearances": 5.0,
          "continuity": 5,
          "avg_rank": 11.5,
          "avg_rank_percentile": 21.7,
          "signal_score": 4.47,
          "avg_gain_pct": 25.41,
          "latest_window": "1d",
          "theme_basis": "產品面推論",
          "theme_confidence": "待覆核",
          "product_label": "軟板材料、FCCL",
          "tier": "S"
        }
      ],
      "tier": 5
    }
  ]
} as const;
