// Generated by analyze_twse_momentum.py. Do not edit manually.
export const report = {
  "generated_at": "2026-08-08T23:52:42.591871+08:00",
  "source_urls": {
    "1d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_1.djhtm",
    "2d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_2.djhtm",
    "3d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_3.djhtm",
    "4d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_4.djhtm",
    "5d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_5.djhtm",
    "10d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_10.djhtm",
    "20d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_20.djhtm"
  },
  "themes": [
    {
      "name": "AI 基礎建設 / 高速傳輸",
      "score": 29,
      "stocks": [
        {
          "code": "6213",
          "name": "聯茂",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 5,
          "avg_rank": 3.4,
          "latest_window": "2d",
          "tier": "S"
        },
        {
          "code": "6426",
          "name": "統新",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 6,
          "avg_rank": 6.2,
          "latest_window": "1d",
          "tier": "S"
        },
        {
          "code": "7711",
          "name": "永擎",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 6,
          "avg_rank": 9.8,
          "latest_window": "2d",
          "tier": "S"
        },
        {
          "code": "6269",
          "name": "台郡",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 5,
          "avg_rank": 16.4,
          "latest_window": "2d",
          "tier": "S"
        },
        {
          "code": "3653",
          "name": "健策",
          "windows": [
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 4,
          "avg_rank": 15.5,
          "latest_window": "4d",
          "tier": "A"
        },
        {
          "code": "3450",
          "name": "聯鈞",
          "windows": [
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 3,
          "avg_rank": 31.3,
          "latest_window": "3d",
          "tier": "A"
        },
        {
          "code": "6805",
          "name": "富世達",
          "windows": [
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 4,
          "avg_rank": 35.8,
          "latest_window": "4d",
          "tier": "A"
        },
        {
          "code": "2455",
          "name": "全新",
          "windows": [
            "4d",
            "5d"
          ],
          "appearances": 2,
          "avg_rank": 38.0,
          "latest_window": "4d",
          "tier": "B"
        },
        {
          "code": "3037",
          "name": "欣興",
          "windows": [
            "5d",
            "10d"
          ],
          "appearances": 2,
          "avg_rank": 40.5,
          "latest_window": "5d",
          "tier": "B"
        }
      ],
      "tier": 1
    },
    {
      "name": "記憶體 / IC 設計",
      "score": 20,
      "stocks": [
        {
          "code": "6531",
          "name": "愛普*",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 5,
          "avg_rank": 13.0,
          "latest_window": "1d",
          "tier": "S"
        },
        {
          "code": "3006",
          "name": "晶豪科",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 5,
          "avg_rank": 15.0,
          "latest_window": "2d",
          "tier": "S"
        },
        {
          "code": "4967",
          "name": "十銓",
          "windows": [
            "4d",
            "10d",
            "20d"
          ],
          "appearances": 3,
          "avg_rank": 18.7,
          "latest_window": "4d",
          "tier": "A"
        },
        {
          "code": "2408",
          "name": "南亞科",
          "windows": [
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 3,
          "avg_rank": 31.7,
          "latest_window": "4d",
          "tier": "A"
        },
        {
          "code": "2344",
          "name": "華邦電",
          "windows": [
            "4d",
            "5d"
          ],
          "appearances": 2,
          "avg_rank": 33.5,
          "latest_window": "4d",
          "tier": "B"
        },
        {
          "code": "4961",
          "name": "天鈺",
          "windows": [
            "2d",
            "3d"
          ],
          "appearances": 2,
          "avg_rank": 37.5,
          "latest_window": "2d",
          "tier": "B"
        },
        {
          "code": "2451",
          "name": "創見",
          "windows": [
            "10d",
            "20d"
          ],
          "appearances": 2,
          "avg_rank": 39.5,
          "latest_window": "10d",
          "tier": "B"
        }
      ],
      "tier": 2
    },
    {
      "name": "機器人 / 智慧製造",
      "score": 18,
      "stocks": [
        {
          "code": "4540",
          "name": "全球傳動",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 6,
          "avg_rank": 13.0,
          "latest_window": "1d",
          "tier": "S"
        },
        {
          "code": "2049",
          "name": "上銀",
          "windows": [
            "1d",
            "3d",
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 6,
          "avg_rank": 22.8,
          "latest_window": "1d",
          "tier": "S"
        },
        {
          "code": "3167",
          "name": "大量",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 4,
          "avg_rank": 18.0,
          "latest_window": "2d",
          "tier": "A"
        },
        {
          "code": "2464",
          "name": "盟立",
          "windows": [
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 3,
          "avg_rank": 19.3,
          "latest_window": "4d",
          "tier": "A"
        },
        {
          "code": "1597",
          "name": "直得",
          "windows": [
            "5d",
            "10d"
          ],
          "appearances": 2,
          "avg_rank": 40.5,
          "latest_window": "5d",
          "tier": "B"
        },
        {
          "code": "4576",
          "name": "大銀微系統",
          "windows": [
            "5d",
            "10d"
          ],
          "appearances": 2,
          "avg_rank": 42.5,
          "latest_window": "5d",
          "tier": "B"
        }
      ],
      "tier": 3
    }
  ]
} as const;
