// Generated by analyze_twse_momentum.py. Do not edit manually.
export const report = {
  "generated_at": "2026-08-10T09:49:38.137340+08:00",
  "market_signature": "07f32eedc7b3565f9d68",
  "freshness": "fresh",
  "last_error": null,
  "source_urls": {
    "1d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_1.djhtm",
    "2d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_2.djhtm",
    "3d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_3.djhtm",
    "4d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_4.djhtm",
    "5d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_5.djhtm",
    "10d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_10.djhtm",
    "20d": "https://fubon-ebrokerdj.fbs.com.tw/z/zg/zg_A_0_20.djhtm"
  },
  "themes": [
    {
      "name": "AI 基礎建設 / 高速傳輸",
      "score": 55,
      "core_strength": 13.24,
      "breadth": 15,
      "provisional_count": 6,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說",
        "歷史題材對照",
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "2059",
          "name": "川湖",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 7,
          "effective_appearances": 5.65,
          "continuity": 7,
          "avg_rank": 5.3,
          "avg_rank_percentile": 8.8,
          "signal_score": 6.0,
          "avg_gain_pct": 27.55,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "中",
          "product_label": "疑似 高階伺服器導軌與機櫃滑軌",
          "is_provisional": true,
          "score_factor": 0.55,
          "llm_review": {
            "product_hypothesis": "高階伺服器導軌與機櫃滑軌",
            "theme_hypotheses": [
              "伺服器機櫃零組件",
              "資料中心基礎設施"
            ],
            "rationale": "多週期動能極強；產品假說指向高階伺服器與機櫃的滑軌零組件。",
            "confidence": "中",
            "source_urls": [
              "https://www.kingslide.com/investor_stockholderservice_basicinfo?___from_store=default&___store=chinese",
              "https://www.kingslide.com/about_intro?___from_store=japanese&___store=chinese"
            ],
            "source_status": "已取得公司官方產品與投資人資料，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "S",
          "raw_tier": "S",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.55,
          "is_new": false,
          "previous_tier": "S",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "6426",
          "name": "統新",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 6,
          "effective_appearances": 5.15,
          "continuity": 6,
          "avg_rank": 6.2,
          "avg_rank_percentile": 10.7,
          "signal_score": 5.37,
          "avg_gain_pct": 23.44,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "光通訊薄膜濾光片與光學鍍膜元件，涵蓋DWDM、CWDM、PON及資料中心400G／800G／1.6T應用",
            "supply_chain_tags": [
              "光通訊被動元件",
              "薄膜濾光片（TFF）",
              "WDM／DWDM",
              "資料中心光互連"
            ],
            "theme_hypotheses": [
              "AI基礎建設",
              "高速光傳輸",
              "矽光子／共同封裝光學（CPO）"
            ],
            "rationale": "官網列示資料中心400G、800G、1.6T及DWDM等產品；公司以TFF為核心。AI與CPO屬資料中心高速互連及公司開發策略之推論，非已揭露營收來源。",
            "confidence": "high",
            "source_urls": [
              "https://www.nextapogee.com.tw/ch/products.php",
              "https://www.nextapogee.com.tw/ch/about.php",
              "https://www.nextapogee.com.tw/cn/investors3-6.php?DownSn=24&opp=download"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "S",
          "raw_tier": "S",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "S",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "6213",
          "name": "聯茂",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 5,
          "effective_appearances": 4.15,
          "continuity": 5,
          "avg_rank": 3.4,
          "avg_rank_percentile": 5.0,
          "signal_score": 4.57,
          "avg_gain_pct": 29.55,
          "latest_window": "2d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "印刷電路板用銅箔基板（CCL）與黏合片（PP），含低損耗、超低損耗及低CTE高速材料",
            "supply_chain_tags": [
              "銅箔基板CCL",
              "黏合片PP",
              "PCB上游材料",
              "高速低損耗材料"
            ],
            "theme_hypotheses": [
              "AI基礎建設",
              "高速傳輸",
              "資料中心／網通交換器"
            ],
            "rationale": "官方年報列CCL、PP為主產品，並開發AI伺服器超低損耗材料；官網稱支援800G／1.6T交換器與PCIe Gen6/7。AI基建屬應用推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.iteqcorp.com/wp-content/uploads/2016/10/112-annual-report-en.pdf",
              "https://www.iteqcorp.com/investor-relations/letter-to-shareholders/?lang=en",
              "https://www.iteqcorp.com/about-iteq/company-profile/?lang=en"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "S",
          "raw_tier": "S",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "S",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "7711",
          "name": "永擎",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 6,
          "effective_appearances": 4.65,
          "continuity": 6,
          "avg_rank": 9.8,
          "avg_rank_percentile": 18.2,
          "signal_score": 4.5,
          "avg_gain_pct": 23.9,
          "latest_window": "2d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "伺服器主機板、整機伺服器及AI GPU高密度液冷伺服器解決方案",
            "supply_chain_tags": [
              "伺服器主機板",
              "AI GPU伺服器",
              "液冷散熱",
              "800Gb/s高速網通"
            ],
            "theme_hypotheses": [
              "AI基礎建設",
              "高速傳輸",
              "資料中心液冷"
            ],
            "rationale": "證交所列主要業務為伺服器主機板及系統；官網產品涵蓋HGX GPU液冷伺服器與800Gb/s OSFP網路。AI基建與高速傳輸為產品應用推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.twse.com.tw/market_insights/zh/detail/8a8216d69a3d6cf9019a8fec866101a9",
              "https://www.asrockrack.com/general/2026Q2_GPU_Server.pdf",
              "https://www.asrockrack.com/general/news.cn.asp?id=280"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "S",
          "raw_tier": "S",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "S",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "6269",
          "name": "台郡",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 5,
          "effective_appearances": 4.15,
          "continuity": 5,
          "avg_rank": 16.4,
          "avg_rank_percentile": 31.8,
          "signal_score": 3.45,
          "avg_gain_pct": 21.56,
          "latest_window": "2d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "軟性印刷電路板（FPC）及高頻高速傳輸模組，涵蓋電／光訊號互連應用",
            "supply_chain_tags": [
              "軟性印刷電路板",
              "高頻高速互連",
              "光電傳輸模組",
              "通訊模組"
            ],
            "theme_hypotheses": [
              "AI高速傳輸",
              "光通訊",
              "5G／毫米波通訊"
            ],
            "rationale": "官方揭露主力為FPC，並開發高速電／光傳輸與高頻模組；AI基礎建設屬其高速互連技術的延伸推論，非已揭露主要營收終端。",
            "confidence": "high",
            "source_urls": [
              "https://www.flexium.com.tw/ProductAndTech/ProductApplication?lang=",
              "https://www.flexium.com.tw/UploadFiles/2025-05-09/202559151121472.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "3605",
          "name": "宏致",
          "windows": [
            "3d",
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 5,
          "effective_appearances": 3.7,
          "continuity": 5,
          "avg_rank": 17.0,
          "avg_rank_percentile": 33.1,
          "signal_score": 3.03,
          "avg_gain_pct": 23.17,
          "latest_window": "3d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "中",
          "product_label": "疑似 連接器與線纜組件",
          "is_provisional": true,
          "score_factor": 0.55,
          "llm_review": {
            "product_hypothesis": "連接器與線纜組件",
            "theme_hypotheses": [
              "高速傳輸",
              "連接器 / 線束"
            ],
            "rationale": "產品可能性聚焦於連接器與線材；是否屬高速傳輸題材須以產品規格與客戶應用確認。",
            "confidence": "中",
            "source_urls": [
              "https://www.acesconn.com/tw/news_detail?id=62"
            ],
            "source_status": "已取得公司官方應用資料，待補第二項官方產品／投資人來源後人工確認",
            "reviewed_at": "2026-08-09"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.55,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "3550",
          "name": "聯穎",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 5,
          "effective_appearances": 4.5,
          "continuity": 5,
          "avg_rank": 26.0,
          "avg_rank_percentile": 51.6,
          "signal_score": 2.85,
          "avg_gain_pct": 14.13,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 高速訊號傳輸線材、線束與連接組件，應用於伺服器、車用、工控及醫療設備。",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "高速訊號傳輸線材、線束與連接組件，應用於伺服器、車用、工控及醫療設備。",
            "supply_chain_tags": [
              "高速傳輸線材",
              "線束組裝",
              "車用線束",
              "伺服器互連"
            ],
            "theme_hypotheses": [
              "AI伺服器與雲端互連",
              "電動車與車用電子",
              "工業自動化"
            ],
            "rationale": "證據：官網與年報列有SFP、SAS、EV、HSD、工控及醫療線材線束。推論：伺服器、車電與自動化為主要成長題材。",
            "confidence": "high",
            "source_urls": [
              "https://www.copartner.com.tw/tw/about/company",
              "https://www.copartner.com.tw/uploads/images/ir/annual-report/2023/tw_ir_manual1130620001.pdf",
              "https://www.twse.com.tw/pdf/ch/3550_ch.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "4566",
          "name": "時碩工業",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "20d"
          ],
          "appearances": 5,
          "effective_appearances": 4.2,
          "continuity": 4,
          "avg_rank": 24.8,
          "avg_rank_percentile": 49.1,
          "signal_score": 2.63,
          "avg_gain_pct": 13.76,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 AI伺服器與高效能運算液冷系統用無滴漏快插式快速接頭（UQD）",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "AI伺服器與高效能運算液冷系統用無滴漏快插式快速接頭（UQD）",
            "supply_chain_tags": [
              "精密金屬零組件",
              "液冷快速接頭",
              "AI伺服器液冷"
            ],
            "theme_hypotheses": [
              "AI資料中心液冷",
              "高效能運算基礎設施"
            ],
            "rationale": "證據：官網明載UQD用於AI伺服器、超級電腦及資料中心液冷，符合OCP標準。推論：可受惠AI／HPC液冷擴建；未證實營收占比。",
            "confidence": "high",
            "source_urls": [
              "https://www.globaltekww.com/tw/universal-quick-disconnect",
              "https://www.globaltekww.com/tw/"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "3653",
          "name": "健策",
          "windows": [
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 4,
          "effective_appearances": 2.8,
          "continuity": 4,
          "avg_rank": 15.5,
          "avg_rank_percentile": 29.6,
          "signal_score": 2.39,
          "avg_gain_pct": 27.13,
          "latest_window": "4d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "高效能運算與半導體封裝用散熱解決方案，涵蓋液冷冷板、先進氣冷、均熱／封裝散熱零組件。",
            "supply_chain_tags": [
              "液冷冷板",
              "氣冷散熱模組",
              "半導體封裝散熱",
              "精密金屬加工"
            ],
            "theme_hypotheses": [
              "AI基礎建設",
              "AI資料中心散熱",
              "高效能運算（HPC）"
            ],
            "rationale": "官網列示HPC之AI資料中心液冷冷板與先進氣冷、封裝散熱件；據此可驗證AI基建散熱，未見高速傳輸為主力的官方證據。",
            "confidence": "high",
            "source_urls": [
              "https://www.jentech.com.tw/zh",
              "https://www.jentech.com.tw/zh/heatspreader",
              "https://www.jentech.com.tw/_files/ugd/e8883b_076092e6ca854d298bdd715fabfabf51.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "3518",
          "name": "柏騰",
          "windows": [
            "1d",
            "2d"
          ],
          "appearances": 2,
          "effective_appearances": 1.95,
          "continuity": 2,
          "avg_rank": 11.0,
          "avg_rank_percentile": 20.9,
          "signal_score": 1.83,
          "avg_gain_pct": 9.86,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 以PVD真空濺鍍為核心，提供半導體先進封裝、散熱／功能鍍膜、碳化矽基板加工及技術服務。",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "以PVD真空濺鍍為核心，提供半導體先進封裝、散熱／功能鍍膜、碳化矽基板加工及技術服務。",
            "supply_chain_tags": [
              "PVD真空濺鍍",
              "半導體先進封裝",
              "散熱材料",
              "碳化矽加工"
            ],
            "theme_hypotheses": [
              "AI伺服器散熱",
              "先進封裝",
              "第三代半導體"
            ],
            "rationale": "證據：官網列示先進封裝、散熱／功能鍍膜與SiC加工；推論：產品可連結AI散熱、先進封裝及第三代半導體需求。",
            "confidence": "high",
            "source_urls": [
              "https://www.pttech.com.tw/",
              "https://www.pttech.com.tw/portfolio-item/advanced-semiconductor-packaging/",
              "https://www.pttech.com.tw/portfolio-item/heat-dissipation-coating/",
              "https://www.pttech.com.tw/portfolio-item/silicon-carbide-machining/"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2425",
          "name": "承啟",
          "windows": [
            "1d",
            "2d",
            "10d",
            "20d"
          ],
          "appearances": 4,
          "effective_appearances": 3.1,
          "continuity": 2,
          "avg_rank": 26.5,
          "avg_rank_percentile": 53.3,
          "signal_score": 1.67,
          "avg_gain_pct": 15.65,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 顯示卡、主機板、電競一體機及AI／通用伺服器軟硬體整合解決方案",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "顯示卡、主機板、電競一體機及AI／通用伺服器軟硬體整合解決方案",
            "supply_chain_tags": [
              "顯示卡",
              "主機板",
              "AI伺服器",
              "系統整合"
            ],
            "theme_hypotheses": [
              "AI伺服器與HPC",
              "電競硬體",
              "生成式AI基礎設施"
            ],
            "rationale": "官網列示顯示卡、主機板、電競一體機、通用與AI伺服器；並稱具AI開發管理平台。推論其受惠主題為AI算力建置與電競硬體需求。",
            "confidence": "high",
            "source_urls": [
              "https://www.chaintech.com.tw/",
              "https://www.chaintech.com.tw/AiServer.aspx?cid=3264"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "6805",
          "name": "富世達",
          "windows": [
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 4,
          "avg_rank": 35.8,
          "avg_gain_pct": 17.53,
          "latest_window": "4d",
          "tier": "B",
          "signal_score": 1.3,
          "continuity": 0,
          "score_factor": 0.4,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 0,
          "previous_tier": "B",
          "tier_change": "down",
          "lifecycle_status": "自然降級",
          "base_score_factor": 1.0
        },
        {
          "code": "3450",
          "name": "聯鈞",
          "windows": [
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 3,
          "avg_rank": 31.3,
          "avg_gain_pct": 18.43,
          "latest_window": "3d",
          "tier": "B",
          "signal_score": 1.18,
          "continuity": 0,
          "score_factor": 0.4,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 0,
          "previous_tier": "B",
          "tier_change": "down",
          "lifecycle_status": "自然降級",
          "base_score_factor": 1.0
        },
        {
          "code": "2455",
          "name": "全新",
          "windows": [
            "4d",
            "5d"
          ],
          "appearances": 2,
          "avg_rank": 38.0,
          "avg_gain_pct": 19.03,
          "latest_window": "4d",
          "tier": "C",
          "signal_score": 0.58,
          "continuity": 0,
          "score_factor": 0.2,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 1,
          "previous_tier": "C",
          "tier_change": "down",
          "lifecycle_status": "C 觀察 1/5",
          "base_score_factor": 1.0
        },
        {
          "code": "3037",
          "name": "欣興",
          "windows": [
            "5d",
            "10d"
          ],
          "appearances": 2,
          "avg_rank": 40.5,
          "avg_gain_pct": 17.59,
          "latest_window": "5d",
          "tier": "C",
          "signal_score": 0.51,
          "continuity": 0,
          "score_factor": 0.2,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 1,
          "previous_tier": "C",
          "tier_change": "down",
          "lifecycle_status": "C 觀察 1/5",
          "base_score_factor": 1.0
        }
      ],
      "tier": 1,
      "active_breadth": 11,
      "cooling_count": 4,
      "lifecycle": "成熟",
      "previous_tier": 1,
      "tier_change": "same"
    },
    {
      "name": "機器人 / 智慧製造",
      "score": 45,
      "core_strength": 10.57,
      "breadth": 7,
      "provisional_count": 1,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說",
        "歷史題材對照",
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "4540",
          "name": "全球傳動",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 6,
          "effective_appearances": 5.15,
          "continuity": 6,
          "avg_rank": 13.0,
          "avg_rank_percentile": 24.9,
          "signal_score": 4.64,
          "avg_gain_pct": 18.88,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "精密線性傳動元件與單軸機器人製造商，主力為滾珠螺桿、線性滑軌及滾珠花鍵。",
            "supply_chain_tags": [
              "滾珠螺桿",
              "線性滑軌",
              "精密傳動元件",
              "單軸機器人"
            ],
            "theme_hypotheses": [
              "機器人",
              "智慧製造",
              "工業自動化"
            ],
            "rationale": "公司年報揭露主力營收為滾珠螺桿及線性滑軌；官網列有單軸機器人，並標示應用於自動化、半導體與工具機。智慧製造屬應用推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.tbimotion.com.tw/zh-TW/",
              "https://www.tbimotion.com.tw/category/single-axis-actuator",
              "https://i0528.tbimotion.com.tw/storage/technical-services/%E5%85%A8%E7%90%83%E5%82%B3%E5%8B%95113%E5%B9%B4%E5%A0%B1-%E4%B8%AD.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "S",
          "raw_tier": "S",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "S",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2049",
          "name": "上銀",
          "windows": [
            "1d",
            "3d",
            "4d",
            "5d",
            "10d",
            "20d"
          ],
          "appearances": 6,
          "effective_appearances": 4.7,
          "continuity": 5,
          "avg_rank": 22.8,
          "avg_rank_percentile": 45.2,
          "signal_score": 3.14,
          "avg_gain_pct": 17.92,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "精密傳動與運動控制元件、工業／半導體機器人及智慧自動化系統",
            "supply_chain_tags": [
              "精密傳動元件",
              "線性滑軌與滾珠螺桿",
              "工業機器人",
              "半導體設備次系統"
            ],
            "theme_hypotheses": [
              "機器人",
              "智慧製造",
              "半導體設備"
            ],
            "rationale": "官網列有滾珠螺桿、線性滑軌、單／多軸機器人、諧波減速機與半導體次系統；智慧螺桿具感測、預診與潤滑功能。機器人及智慧製造主題具直接產品佐證。",
            "confidence": "high",
            "source_urls": [
              "https://www.hiwin.tw/",
              "https://www.hiwin.tw/products/ballscrew/i40bs.aspx",
              "https://www.hiwin.tw/products/single_axis_robot/single_axis_robot_list.aspx",
              "https://esg.hiwin.tw/en/ch3/ch3_1.aspx"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "down",
          "lifecycle_status": "自然降級"
        },
        {
          "code": "3167",
          "name": "大量",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 4,
          "effective_appearances": 3.5,
          "continuity": 4,
          "avg_rank": 18.0,
          "avg_rank_percentile": 35.2,
          "signal_score": 2.79,
          "avg_gain_pct": 24.11,
          "latest_window": "2d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "PCB鑽孔與成型設備、半導體先進封裝AOI／量測及自動化設備製造商",
            "supply_chain_tags": [
              "PCB製程設備",
              "半導體先進封裝檢測",
              "AOI與量測設備",
              "製造自動化"
            ],
            "theme_hypotheses": [
              "智慧製造",
              "先進封裝",
              "AI伺服器PCB"
            ],
            "rationale": "官方產品頁列PCB加工、CMP與封裝AOI／量測及搬運自動化設備；智慧製造有MES監控與AGV佐證。機器人僅可視為自動化延伸，非主產品。",
            "confidence": "high",
            "source_urls": [
              "https://www.tlhome.com.tw/",
              "https://www.tlhome.com.tw/category/5",
              "https://www.tlhome.com.tw/category/1",
              "https://www.tlhome.com.tw/about/11"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2464",
          "name": "盟立",
          "windows": [
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 3,
          "effective_appearances": 2.3,
          "continuity": 3,
          "avg_rank": 19.3,
          "avg_rank_percentile": 37.6,
          "signal_score": 1.78,
          "avg_gain_pct": 21.69,
          "latest_window": "4d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "工業智慧自動化與半導體廠內搬送系統，並布局AMR、AI人形及足式機器人平台",
            "supply_chain_tags": [
              "工廠自動化系統整合",
              "半導體AMHS／EFEM",
              "AGV／AMR自主搬運",
              "機器人關節與減速機"
            ],
            "theme_hypotheses": [
              "機器人／具身智能",
              "智慧製造",
              "半導體自動化"
            ],
            "rationale": "官方產品頁列示半導體搬送、AGV/AMR與AI機器人；具身智能與智慧製造為其已揭露布局，商業化規模仍屬推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.mirle.com.tw/product_introduction/",
              "https://www.mirle.com.tw/product_introduction/115/",
              "https://www.mirle.com.tw/news-detail/661/",
              "https://www.mirle.com.tw/product_introduction-detail/209/"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "3652",
          "name": "精聯",
          "windows": [
            "2d",
            "3d",
            "4d"
          ],
          "appearances": 3,
          "effective_appearances": 2.7,
          "continuity": 3,
          "avg_rank": 29.3,
          "avg_rank_percentile": 58.1,
          "signal_score": 1.54,
          "avg_gain_pct": 12.37,
          "latest_window": "2d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 自動資料收集（AIDC）設備與軟體整合方案，主力為強固型PDA、條碼掃描器、RFID讀取器及行動裝置管理平台。",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "自動資料收集（AIDC）設備與軟體整合方案，主力為強固型PDA、條碼掃描器、RFID讀取器及行動裝置管理平台。",
            "supply_chain_tags": [
              "AIDC自動資料收集",
              "強固型行動電腦",
              "條碼掃描",
              "RFID讀取器"
            ],
            "theme_hypotheses": [
              "智慧物流與倉儲數位化",
              "智慧製造與工業自動化",
              "零售與醫療行動化管理"
            ],
            "rationale": "官方明示三大產品與軟硬體整合，並列物流、倉儲、製造、零售及醫療應用；上述市場主題為依其應用場景所作推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.ute.com/tw/about",
              "https://www.ute-cn.com/tw/ir/shareholder/meeting"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "1597",
          "name": "直得",
          "windows": [
            "5d",
            "10d"
          ],
          "appearances": 2,
          "avg_rank": 40.5,
          "avg_gain_pct": 17.79,
          "latest_window": "5d",
          "tier": "C",
          "signal_score": 0.51,
          "continuity": 0,
          "score_factor": 0.2,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 1,
          "previous_tier": "C",
          "tier_change": "down",
          "lifecycle_status": "C 觀察 1/5",
          "base_score_factor": 1.0
        },
        {
          "code": "4576",
          "name": "大銀微系統",
          "windows": [
            "5d",
            "10d"
          ],
          "appearances": 2,
          "avg_rank": 42.5,
          "avg_gain_pct": 17.31,
          "latest_window": "5d",
          "tier": "C",
          "signal_score": 0.45,
          "continuity": 0,
          "score_factor": 0.2,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 1,
          "previous_tier": "C",
          "tier_change": "down",
          "lifecycle_status": "C 觀察 1/5",
          "base_score_factor": 1.0
        }
      ],
      "tier": 2,
      "active_breadth": 5,
      "cooling_count": 2,
      "lifecycle": "成熟",
      "previous_tier": 2,
      "tier_change": "same"
    },
    {
      "name": "記憶體 / IC 設計",
      "score": 38,
      "core_strength": 9.05,
      "breadth": 7,
      "provisional_count": 0,
      "early_cluster_count": 0,
      "mapping_basis": [
        "歷史題材對照",
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "6531",
          "name": "愛普*",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 5,
          "effective_appearances": 4.5,
          "continuity": 5,
          "avg_rank": 13.0,
          "avg_rank_percentile": 25.2,
          "signal_score": 4.04,
          "avg_gain_pct": 21.44,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "無晶圓廠客製化記憶體與IP解決方案商，提供IoTRAM（PSRAM、LPDDR）、S-SiCap矽電容及VHM 3D高頻寬記憶體方案。",
            "supply_chain_tags": [
              "無晶圓廠IC設計",
              "利基型記憶體",
              "矽電容/IP授權",
              "3D異質整合"
            ],
            "theme_hypotheses": [
              "物聯網與低功耗終端記憶體",
              "邊緣AI與高效能運算",
              "Chiplet／3D堆疊記憶體"
            ],
            "rationale": "官方明示其為客製化記憶體設計及IP公司，產品涵蓋PSRAM、LPDDR、矽電容與VHM；IoT、AI/HPC及Chiplet為產品應用與延伸主題。",
            "confidence": "high",
            "source_urls": [
              "https://www.apmemory.com/tw/about/company",
              "https://www.apmemory.com/tw/product/iotram",
              "https://www.apmemory.com/tw/product/SiCap",
              "https://www.apmemory.com/tw/solution/VHM"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "S",
          "raw_tier": "S",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "S",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "3006",
          "name": "晶豪科",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 5,
          "effective_appearances": 4.15,
          "continuity": 5,
          "avg_rank": 15.0,
          "avg_rank_percentile": 29.0,
          "signal_score": 3.57,
          "avg_gain_pct": 24.36,
          "latest_window": "2d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "利基型記憶體及類比／混合訊號IC設計，涵蓋DRAM、Flash、MCP、PSRAM與電源／音訊等產品",
            "supply_chain_tags": [
              "IC設計",
              "利基型DRAM",
              "NOR／NAND Flash",
              "多晶片封裝MCP"
            ],
            "theme_hypotheses": [
              "利基型記憶體",
              "車用電子",
              "AI邊緣運算／記憶體內運算"
            ],
            "rationale": "證據：官網列示DRAM、Flash、MCP、PSRAM及類比產品，並標示工控、車用與AI邊緣應用；據此歸納為利基型記憶體IC設計商。",
            "confidence": "high",
            "source_urls": [
              "https://www.esmt.com.tw/tw",
              "https://www.esmt.com.tw/zh-tw/Products",
              "https://www.esmt.com.tw/zh-tw/Applications",
              "https://www.esmt.com.tw/tw/about/introduction"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "S",
          "raw_tier": "S",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "S",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "4967",
          "name": "十銓",
          "windows": [
            "4d",
            "10d",
            "20d"
          ],
          "appearances": 3,
          "effective_appearances": 2.0,
          "continuity": 2,
          "avg_rank": 18.7,
          "avg_rank_percentile": 36.4,
          "signal_score": 1.44,
          "avg_gain_pct": 21.66,
          "latest_window": "4d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "自有品牌DRAM記憶體模組、SSD固態硬碟、記憶卡與工業級嵌入式儲存產品",
            "supply_chain_tags": [
              "DRAM記憶體模組",
              "NAND Flash／SSD",
              "消費性儲存品牌",
              "工業級嵌入式儲存"
            ],
            "theme_hypotheses": [
              "記憶體與快閃儲存",
              "工業電腦／邊緣AI",
              "電競與創作者高效能儲存"
            ],
            "rationale": "官方產品與年報證實主力為記憶體模組、SSD、記憶卡及工控儲存；AI邊緣與工控自動化為公司研發布局，非IC設計公司。",
            "confidence": "high",
            "source_urls": [
              "https://www.teamgroupinc.com/tw/about/vision/",
              "https://www.teamgroupinc.com/tw/product-brand/memory/TEAMGROUP/",
              "https://industrial.teamgroupinc.com/products/",
              "https://file.teamgroupinc.com/about/shareholders-meeting-information/114/annual-report.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2408",
          "name": "南亞科",
          "windows": [
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 3,
          "avg_rank": 31.7,
          "avg_gain_pct": 18.67,
          "latest_window": "4d",
          "tier": "B",
          "signal_score": 1.16,
          "continuity": 0,
          "score_factor": 0.4,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 0,
          "previous_tier": "B",
          "tier_change": "down",
          "lifecycle_status": "自然降級",
          "base_score_factor": 1.0
        },
        {
          "code": "2344",
          "name": "華邦電",
          "windows": [
            "4d",
            "5d"
          ],
          "appearances": 2,
          "avg_rank": 33.5,
          "avg_gain_pct": 20.05,
          "latest_window": "4d",
          "tier": "C",
          "signal_score": 0.72,
          "continuity": 0,
          "score_factor": 0.2,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 1,
          "previous_tier": "C",
          "tier_change": "down",
          "lifecycle_status": "C 觀察 1/5",
          "base_score_factor": 1.0
        },
        {
          "code": "4961",
          "name": "天鈺",
          "windows": [
            "2d",
            "3d"
          ],
          "appearances": 2,
          "avg_rank": 37.5,
          "avg_gain_pct": 9.53,
          "latest_window": "2d",
          "tier": "C",
          "signal_score": 0.6,
          "continuity": 0,
          "score_factor": 0.2,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 1,
          "previous_tier": "C",
          "tier_change": "down",
          "lifecycle_status": "C 觀察 1/5",
          "base_score_factor": 1.0
        },
        {
          "code": "2451",
          "name": "創見",
          "windows": [
            "10d",
            "20d"
          ],
          "appearances": 2,
          "avg_rank": 39.5,
          "avg_gain_pct": 14.83,
          "latest_window": "10d",
          "tier": "C",
          "signal_score": 0.54,
          "continuity": 0,
          "score_factor": 0.2,
          "is_provisional": false,
          "theme_basis": "歷史題材對照",
          "raw_tier": null,
          "is_active": false,
          "is_new": false,
          "miss_streak": 1,
          "c_stagnant_days": 1,
          "previous_tier": "C",
          "tier_change": "down",
          "lifecycle_status": "C 觀察 1/5",
          "base_score_factor": 1.0
        }
      ],
      "tier": 3,
      "active_breadth": 3,
      "cooling_count": 4,
      "lifecycle": "成熟",
      "previous_tier": 3,
      "tier_change": "same"
    },
    {
      "name": "金屬材料 / 資源循環",
      "score": 32,
      "core_strength": 7.63,
      "breadth": 2,
      "provisional_count": 0,
      "early_cluster_count": 0,
      "mapping_basis": [
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "7610",
          "name": "聯友金屬-創",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 5,
          "effective_appearances": 4.5,
          "continuity": 5,
          "avg_rank": 7.6,
          "avg_rank_percentile": 14.0,
          "signal_score": 4.54,
          "avg_gain_pct": 28.72,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "鎢、鈷關鍵金屬回收、純化與材料",
            "theme_hypotheses": [
              "金屬材料",
              "資源循環"
            ],
            "rationale": "公司官方資料指出其回收二次硬質合金及鎢、鈷資源，製造高純度鈷產品與相關化合物；仍不直接納入正式題材。",
            "confidence": "中",
            "source_urls": [
              "https://www.lianyoucorp.com/TW",
              "https://wwwc.twse.com.tw/market_insights/zh/detail/8a8216d697fc438f01992763eeec04c9"
            ],
            "source_status": "已取得公司官方產品資料與交易所公司介紹，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "S",
          "raw_tier": "S",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "S",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2031",
          "name": "新光鋼",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "10d",
            "20d"
          ],
          "appearances": 6,
          "effective_appearances": 4.85,
          "continuity": 4,
          "avg_rank": 23.0,
          "avg_rank_percentile": 45.6,
          "signal_score": 3.09,
          "avg_gain_pct": 14.67,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "鋼材通路、裁剪加工與鋼結構製造服務，供應中厚板、熱冷軋、鍍鋅、不鏽鋼及特殊鋼。",
            "supply_chain_tags": [
              "鋼材通路",
              "鋼材裁剪加工",
              "鋼結構製造",
              "鋼品物流"
            ],
            "theme_hypotheses": [
              "公共工程與基礎建設",
              "半導體與科技廠房建設"
            ],
            "rationale": "官方證實其供應多類鋼材並提供裁剪、供料及BOX/BH鋼構製造；公共工程與科技廠房為已揭露案例，相關市場主題屬合理推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.hkssteel.com.tw/",
              "https://www.hkssteel.com.tw/abo_bus.html",
              "https://www.hkssteel.com.tw/ser_page02.html",
              "https://www.hkssteel.com.tw/ser_page03.html"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 4,
      "active_breadth": 2,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 4,
      "tier_change": "same"
    },
    {
      "name": "光電 / 電子零組件",
      "score": 27,
      "core_strength": 6.49,
      "breadth": 2,
      "provisional_count": 0,
      "early_cluster_count": 0,
      "mapping_basis": [
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "2491",
          "name": "吉祥全",
          "windows": [
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 4,
          "effective_appearances": 3.5,
          "continuity": 4,
          "avg_rank": 8.8,
          "avg_rank_percentile": 16.0,
          "signal_score": 3.46,
          "avg_gain_pct": 24.92,
          "latest_window": "2d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "光電照明應用產品、電子零組件與資訊產品",
            "theme_hypotheses": [
              "光電照明",
              "電子零組件"
            ],
            "rationale": "公司永續報告列示光電照明應用產品、電子應用產品與零組件；終端動能題材仍不足以直接升格。",
            "confidence": "中",
            "source_urls": [
              "https://www.focl.com.tw/investor.php?PID=8",
              "https://www.focl.com.tw/userfiles/files/%E6%B0%B8%E7%BA%8C%E7%99%BC%E5%B1%95/FOCL_Sustainability%20Report.pdf"
            ],
            "source_status": "已取得公司官方投資人與永續資料，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2426",
          "name": "鼎元",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 5,
          "effective_appearances": 4.5,
          "continuity": 5,
          "avg_rank": 24.0,
          "avg_rank_percentile": 47.6,
          "signal_score": 3.03,
          "avg_gain_pct": 16.7,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "LED、紅外線與光纖通訊用化合物半導體及矽光電晶片",
            "supply_chain_tags": [
              "LED晶粒",
              "紅外線LED晶粒",
              "矽光電感測晶片",
              "光通訊晶片"
            ],
            "theme_hypotheses": [
              "紅外線感測",
              "光纖通訊",
              "LED照明／顯示"
            ],
            "rationale": "官網列示可見光與紅外線LED、矽光感測及InP基光通訊晶片；照明／顯示與感測終端應用屬產品組合推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.tyntek.com.tw/en/products.php",
              "https://www.tyntek.com.tw/en/products_02.php",
              "https://www.tyntek.com.tw/en/products04.php"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 5,
      "active_breadth": 2,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 5,
      "tier_change": "same"
    },
    {
      "name": "生技醫療 / 製藥",
      "score": 25,
      "core_strength": 5.82,
      "breadth": 3,
      "provisional_count": 2,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說",
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "6782",
          "name": "視陽",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "10d"
          ],
          "appearances": 5,
          "effective_appearances": 4.35,
          "continuity": 4,
          "avg_rank": 23.4,
          "avg_rank_percentile": 46.5,
          "signal_score": 2.83,
          "avg_gain_pct": 12.92,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 矽水膠拋棄式隱形眼鏡，涵蓋近遠視、老花、散光、抗藍光及彩色款",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "矽水膠拋棄式隱形眼鏡，涵蓋近遠視、老花、散光、抗藍光及彩色款",
            "supply_chain_tags": [
              "矽水膠隱形眼鏡",
              "拋棄式隱形眼鏡製造",
              "視力矯正產品",
              "彩色隱形眼鏡"
            ],
            "theme_hypotheses": [
              "視力矯正需求",
              "矽水膠隱形眼鏡升級",
              "彩色隱形眼鏡"
            ],
            "rationale": "證據：官網列示全系列矽水膠隱形眼鏡，含近遠視、老花、散光、抗藍光與彩色款；推論：可對應視力矯正及彩片需求主題。",
            "confidence": "high",
            "source_urls": [
              "https://www.visco.com.tw/tw/business_overview.html",
              "https://visco.com.tw/en/about_history.html",
              "https://wwwc.twse.com.tw/pdf/ch/6782_ch.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "1762",
          "name": "中化生",
          "windows": [
            "1d",
            "2d",
            "3d"
          ],
          "appearances": 3,
          "effective_appearances": 2.85,
          "continuity": 3,
          "avg_rank": 18.7,
          "avg_rank_percentile": 36.3,
          "signal_score": 2.24,
          "avg_gain_pct": 10.57,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "原料藥與醫藥中間體",
            "theme_hypotheses": [
              "原料藥 / 製藥",
              "生技醫療"
            ],
            "rationale": "公司名稱與市場既有認知指向製藥供應鏈；仍須以官方產品線確認細分領域。",
            "confidence": "中",
            "source_urls": [
              "https://www.ccsb.com.tw/upfiles/ADUpload/tw_ir2366714228.pdf",
              "https://www.ccsb.com.tw/upfiles/ADUpload/tw_be_ir1mul2_3397525592.pdf"
            ],
            "source_status": "已取得公司官方投資人資料，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "3716",
          "name": "中化控股",
          "windows": [
            "1d",
            "2d"
          ],
          "appearances": 2,
          "effective_appearances": 1.95,
          "continuity": 2,
          "avg_rank": 22.0,
          "avg_rank_percentile": 44.1,
          "signal_score": 1.38,
          "avg_gain_pct": 8.96,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 處方藥、特殊製劑與學名藥製造，結合OTC／保健、動物健康及銀髮照護服務",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "處方藥、特殊製劑與學名藥製造，結合OTC／保健、動物健康及銀髮照護服務",
            "supply_chain_tags": [
              "藥品製造",
              "CDMO委託開發製造",
              "處方藥與OTC通路",
              "長照服務"
            ],
            "theme_hypotheses": [
              "高門檻學名藥與特殊製劑CDMO",
              "消費者健康與OTC數位通路",
              "高齡照護"
            ],
            "rationale": "證據：年報列示藥品、OTC、動藥及銀髮照護，並規劃高門檻製劑CDMO。推論：成長主題為CDMO、消費健康與高齡照護。",
            "confidence": "high",
            "source_urls": [
              "https://www.cenra.com/tw/about/company",
              "https://www.cenra.com/tw/financial/annual",
              "https://www.cenra.com/uploads/images/Invester/annual-report/2025.pdf",
              "https://www.cenra-pharma.com/tw/financial-reports"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 6,
      "active_breadth": 3,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 6,
      "tier_change": "same"
    },
    {
      "name": "電力控制 / 工業自動化",
      "score": 24,
      "core_strength": 5.7,
      "breadth": 2,
      "provisional_count": 1,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說",
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "7788",
          "name": "松川精密",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 6,
          "effective_appearances": 5.15,
          "continuity": 6,
          "avg_rank": 21.5,
          "avg_rank_percentile": 42.4,
          "signal_score": 3.74,
          "avg_gain_pct": 15.8,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "電磁繼電器、接觸器與高壓直流繼電器",
            "theme_hypotheses": [
              "繼電器 / 電控零組件",
              "工業自動化"
            ],
            "rationale": "產品可能性聚焦於電控與繼電器應用；是否形成工業自動化題材仍需以官方產品與終端應用確認。",
            "confidence": "中",
            "source_urls": [
              "https://www.songchuan.com/sc/",
              "https://www.songchuan.com/sc/wp-content/uploads/2024/12/3-1-%E6%B3%95%E4%BA%BA%E8%AA%AA%E6%98%8E%E6%9C%83%E7%B0%A1%E5%A0%B1_%E4%B8%AD%E6%96%8720241022.pdf"
            ],
            "source_status": "已取得公司官方產品與法說資料，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2397",
          "name": "友通",
          "windows": [
            "1d",
            "3d",
            "4d",
            "5d"
          ],
          "appearances": 4,
          "effective_appearances": 3.55,
          "continuity": 3,
          "avg_rank": 23.2,
          "avg_rank_percentile": 45.9,
          "signal_score": 2.3,
          "avg_gain_pct": 16.41,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 工業嵌入式主機板、邊緣運算系統與工業級觸控電腦",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "工業嵌入式主機板、邊緣運算系統與工業級觸控電腦",
            "supply_chain_tags": [
              "工業電腦",
              "嵌入式主機板",
              "邊緣AI運算",
              "工業觸控電腦"
            ],
            "theme_hypotheses": [
              "工業自動化",
              "邊緣AI／AIoT",
              "智慧交通與智慧醫療"
            ],
            "rationale": "證據：年報明載公司研發製造嵌入式主機板、邊緣運算系統及工業觸控電腦。推論：其垂直應用布局可受惠工業自動化與邊緣AI需求。",
            "confidence": "high",
            "source_urls": [
              "https://www.dfi.com/Uploads/InvestorRelation/3027b8ad-4ff4-49da-a05b-b22db8f1c169/%E5%8F%8B%E9%80%9A%E8%B3%87%E8%A8%8A115%E5%B8%B8%E6%9C%83-%E4%B8%AD%E6%96%87%E5%B9%B4%E5%A0%B1.pdf?timestamp=1778140593.72025",
              "https://blog.dfi.com/zh-tw/dfi-ec600-rps-premium-edge-ai-platform-featured-in-intel-partner-spotlight"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 7,
      "active_breadth": 2,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 7,
      "tier_change": "same"
    },
    {
      "name": "特用化學 / 高階材料",
      "score": 23,
      "core_strength": 5.62,
      "breadth": 2,
      "provisional_count": 0,
      "early_cluster_count": 0,
      "mapping_basis": [
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "2103",
          "name": "台橡",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d"
          ],
          "appearances": 4,
          "effective_appearances": 3.7,
          "continuity": 4,
          "avg_rank": 15.8,
          "avg_rank_percentile": 30.4,
          "signal_score": 3.13,
          "avg_gain_pct": 13.53,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "合成橡膠與高分子材料",
            "theme_hypotheses": [
              "合成橡膠",
              "特用化學材料"
            ],
            "rationale": "產品可能性聚焦於合成橡膠與材料化工供應鏈。",
            "confidence": "中",
            "source_urls": [
              "https://www.tsrc.com.tw/tw/products-services/",
              "https://www.tsrc.com.tw/tw/products-services/product-finder/"
            ],
            "source_status": "已取得公司官方產品資料，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "4722",
          "name": "國精化",
          "windows": [
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 4,
          "effective_appearances": 3.2,
          "continuity": 4,
          "avg_rank": 19.0,
          "avg_rank_percentile": 37.1,
          "signal_score": 2.49,
          "avg_gain_pct": 22.16,
          "latest_window": "3d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "特用化學與電子／工業材料",
            "theme_hypotheses": [
              "特用化學",
              "材料升級"
            ],
            "rationale": "屬材料化工方向的初步假說，尚不應連結至特定終端題材。",
            "confidence": "低",
            "source_urls": [
              "https://www.qualipoly.com/zh-tw/product.html",
              "https://www.qualipoly.com/zh-tw/news-c2293/%E5%85%AC%E5%8F%B8%E7%9B%B8%E9%97%9C%E5%A0%B1%E5%B0%8E.html"
            ],
            "source_status": "已取得公司官方產品資料，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 8,
      "active_breadth": 2,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 8,
      "tier_change": "same"
    },
    {
      "name": "營建 / 不動產",
      "score": 16,
      "core_strength": 3.53,
      "breadth": 3,
      "provisional_count": 3,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說"
      ],
      "stocks": [
        {
          "code": "2006",
          "name": "東和鋼鐵",
          "windows": [
            "2d",
            "10d",
            "20d"
          ],
          "appearances": 3,
          "effective_appearances": 2.1,
          "continuity": 2,
          "avg_rank": 9.7,
          "avg_rank_percentile": 18.1,
          "signal_score": 1.87,
          "avg_gain_pct": 20.74,
          "latest_window": "2d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 建築用鋼材製造與加工服務商，主力為鋼筋、H型鋼等型鋼、熱軋鋼板，並提供鋼筋裁剪彎曲、鋼筋網及組合H型鋼加工。",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "建築用鋼材製造與加工服務商，主力為鋼筋、H型鋼等型鋼、熱軋鋼板，並提供鋼筋裁剪彎曲、鋼筋網及組合H型鋼加工。",
            "supply_chain_tags": [
              "建築鋼筋",
              "結構型鋼",
              "熱軋鋼板",
              "鋼材加工配送"
            ],
            "theme_hypotheses": [
              "耐震建築",
              "公共工程與營建",
              "營建鋼材一站式供應"
            ],
            "rationale": "官方產品頁列鋼筋、型鋼、鋼板及加工服務，並指向建築、橋梁等用途；耐震建築與一站式供應為依產品規格及加工內容所作推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.tunghosteel.com/Product/Intro/1",
              "https://www.tunghosteel.com/Product/Intro/2",
              "https://www.tunghosteel.com/Product/Intro/3",
              "https://www.tunghosteel.com/Product/Intro/4"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2536",
          "name": "宏普",
          "windows": [
            "1d",
            "2d"
          ],
          "appearances": 2,
          "effective_appearances": 1.95,
          "continuity": 2,
          "avg_rank": 26.5,
          "avg_rank_percentile": 53.5,
          "signal_score": 1.2,
          "avg_gain_pct": 8.23,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 大台北住宅、商辦及廠辦電梯大樓之開發、興建、出售與租賃",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "大台北住宅、商辦及廠辦電梯大樓之開發、興建、出售與租賃",
            "supply_chain_tags": [
              "不動產開發",
              "住宅大樓",
              "商辦大樓",
              "廠辦大樓"
            ],
            "theme_hypotheses": [
              "大台北都會區不動產開發",
              "都市更新與聯合開發",
              "綠色建築與永續營造"
            ],
            "rationale": "官方報告明示主業為住宅、商辦及廠辦大樓興建與租賃，內銷為主；都市更新及永續營造為依官網業務與ESG內容延伸之主題推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.hong-pu.com.tw/tw/esg/report",
              "https://www.hong-pu.com.tw/uploads/images/esg/%E5%AE%8F%E6%99%AE%E5%BB%BA%E8%A8%AD2024ESG%E5%A0%B1%E5%91%8A%E6%9B%B8.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2527",
          "name": "宏璟",
          "windows": [
            "2d",
            "3d"
          ],
          "appearances": 2,
          "effective_appearances": 1.85,
          "continuity": 2,
          "avg_rank": 28.5,
          "avg_rank_percentile": 56.5,
          "signal_score": 1.08,
          "avg_gain_pct": 10.43,
          "latest_window": "2d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 住宅、商業大樓及智慧型工業廠辦之開發、出租與銷售，並經營社區型商場",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "住宅、商業大樓及智慧型工業廠辦之開發、出租與銷售，並經營社區型商場",
            "supply_chain_tags": [
              "住宅開發",
              "商業不動產",
              "工業廠辦",
              "商場營運"
            ],
            "theme_hypotheses": [
              "台灣不動產開發",
              "智慧綠建築",
              "工業廠辦開發"
            ],
            "rationale": "證據：官網稱業務涵蓋住商廠辦、租賃及商場，並開發綠建築與智慧型工業廠辦；推論：主題聚焦不動產與廠辦開發。",
            "confidence": "high",
            "source_urls": [
              "https://mis281.wixsite.com/asehcc/about",
              "https://wwwc.twse.com.tw/pdf/ch/2527_ch.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 9,
      "active_breadth": 3,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 9,
      "tier_change": "same"
    },
    {
      "name": "電商 / 數位支付",
      "score": 16,
      "core_strength": 3.83,
      "breadth": 2,
      "provisional_count": 2,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說"
      ],
      "stocks": [
        {
          "code": "8454",
          "name": "富邦媒",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "10d"
          ],
          "appearances": 5,
          "effective_appearances": 4.35,
          "continuity": 4,
          "avg_rank": 26.8,
          "avg_rank_percentile": 53.2,
          "signal_score": 2.55,
          "avg_gain_pct": 12.71,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 以momo購物網、行動App、電視購物及商城提供商品銷售與配送服務的全通路電商平台。",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "以momo購物網、行動App、電視購物及商城提供商品銷售與配送服務的全通路電商平台。",
            "supply_chain_tags": [
              "B2C電商",
              "第三方賣家平台",
              "自動化物流",
              "電視購物"
            ],
            "theme_hypotheses": [
              "台灣電商",
              "平台經濟",
              "物流自動化"
            ],
            "rationale": "證據：官方列示購物網、電視購物、商城與App，並展示自動化物流系統。推論：3P擴張可望強化平台電商與物流效率主題。",
            "confidence": "high",
            "source_urls": [
              "https://corp.momo.com.tw/investor/faq",
              "https://corp.momo.com.tw/",
              "https://corp.momo.com.tw/investor/investorActivity"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "7722",
          "name": "LINEPAY",
          "windows": [
            "1d",
            "2d",
            "3d"
          ],
          "appearances": 3,
          "effective_appearances": 2.85,
          "continuity": 3,
          "avg_rank": 23.3,
          "avg_rank_percentile": 46.1,
          "signal_score": 1.96,
          "avg_gain_pct": 10.65,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 提供消費者付款、轉帳與生活繳費，以及商家線上、POS、QR收款與點數行銷的行動支付平台",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "提供消費者付款、轉帳與生活繳費，以及商家線上、POS、QR收款與點數行銷的行動支付平台",
            "supply_chain_tags": [
              "第三方支付",
              "電子支付",
              "商戶收款",
              "行銷科技"
            ],
            "theme_hypotheses": [
              "金融科技",
              "無現金支付",
              "商戶數位轉型"
            ],
            "rationale": "官網證實其涵蓋商家收款串接、LINE Pay Money儲值轉帳與生活繳費、點數／優惠券行銷；金融科技與商戶數位轉型為據此延伸之主題歸類。",
            "confidence": "high",
            "source_urls": [
              "https://pay.line.me/portal/tw/business/payment-service?locale=zh_TW",
              "https://pay.line.me/portal/tw-lpm/",
              "https://pay.line.me/portal/tw/business/marketing"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 10,
      "active_breadth": 2,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 10,
      "tier_change": "same"
    },
    {
      "name": "半導體 IP / RISC-V",
      "score": 13,
      "core_strength": 3.21,
      "breadth": 1,
      "provisional_count": 0,
      "early_cluster_count": 0,
      "mapping_basis": [
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "6533",
          "name": "晶心科",
          "windows": [
            "1d",
            "2d",
            "3d",
            "10d",
            "20d"
          ],
          "appearances": 5,
          "effective_appearances": 4.0,
          "continuity": 3,
          "avg_rank": 13.4,
          "avg_rank_percentile": 25.8,
          "signal_score": 3.21,
          "avg_gain_pct": 17.42,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "RISC-V CPU IP 與處理器設計服務",
            "theme_hypotheses": [
              "RISC-V",
              "半導體 IP / CPU"
            ],
            "rationale": "產品可能性指向處理器 IP；是否與特定 AI 運算題材連結，需依產品與營收應用確認。",
            "confidence": "中",
            "source_urls": [
              "https://www.andestech.com/tw/",
              "https://www.sipa.gov.tw/home.jsp?contlink=ap%2Fmanufacturers_3_1.jsp&dataserno=202101080001&level2=Y&menudata=ChineseMenu&mserno=201001210001&serno=2010012002"
            ],
            "source_status": "已取得公司官方產品資料與園區資料，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 11,
      "active_breadth": 1,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 11,
      "tier_change": "same"
    },
    {
      "name": "儲能 / 電池",
      "score": 12,
      "core_strength": 2.89,
      "breadth": 1,
      "provisional_count": 0,
      "early_cluster_count": 0,
      "mapping_basis": [
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "6781",
          "name": "AES-KY",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 6,
          "effective_appearances": 5.15,
          "continuity": 6,
          "avg_rank": 29.3,
          "avg_rank_percentile": 58.8,
          "signal_score": 2.89,
          "avg_gain_pct": 14.25,
          "latest_window": "1d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "動力與儲能鋰電池模組，供輕量電動載具及資料中心／工業備援儲能系統使用",
            "supply_chain_tags": [
              "鋰電池模組",
              "電池管理系統（BMS）",
              "熱管理",
              "工業備援儲能"
            ],
            "theme_hypotheses": [
              "電動二輪車",
              "資料中心備援電力",
              "儲能系統"
            ],
            "rationale": "官網明示產品為動力及儲能鋰電池模組，應用於電動自行車、電動機車與資料中心備用電池；上述市場主題為依應用場景所作推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.advancedenergysolution.com.tw/article.php?cid=172&lang=tw&tb=3",
              "https://www.advancedenergysolution.com.tw/article.php?lang=tw&tb=1",
              "https://www.twse.com.tw/staticFiles/news/news/tsecnews/ff80808174fce5b301754a6b8210013a.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 12,
      "active_breadth": 1,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 12,
      "tier_change": "same"
    },
    {
      "name": "PCB / 高階材料",
      "score": 10,
      "core_strength": 2.46,
      "breadth": 1,
      "provisional_count": 1,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說"
      ],
      "stocks": [
        {
          "code": "8039",
          "name": "台虹",
          "windows": [
            "1d",
            "2d",
            "3d",
            "4d",
            "5d",
            "20d"
          ],
          "appearances": 6,
          "effective_appearances": 5.0,
          "continuity": 5,
          "avg_rank": 11.5,
          "avg_rank_percentile": 21.7,
          "signal_score": 4.47,
          "avg_gain_pct": 25.41,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "中",
          "product_label": "疑似 軟性銅箔基板（FCCL）與軟板材料",
          "is_provisional": true,
          "score_factor": 0.55,
          "llm_review": {
            "product_hypothesis": "軟性銅箔基板（FCCL）與軟板材料",
            "theme_hypotheses": [
              "軟板材料 / FCCL",
              "電子材料"
            ],
            "rationale": "產品假說指向軟板上游材料；需與公司產品資料核對後才可升格 Mapping。",
            "confidence": "中",
            "source_urls": [
              "https://www.taiflex.com.tw/ESG/Pro_Quality",
              "https://www.taiflex.com.tw/ESG/Pro_Market"
            ],
            "source_status": "已取得公司官方產品資料，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "S",
          "raw_tier": "S",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.55,
          "is_new": false,
          "previous_tier": "S",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 13,
      "active_breadth": 1,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 13,
      "tier_change": "same"
    },
    {
      "name": "邊緣 AI / AIoT",
      "score": 10,
      "core_strength": 2.29,
      "breadth": 2,
      "provisional_count": 2,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說"
      ],
      "stocks": [
        {
          "code": "5484",
          "name": "慧友",
          "windows": [
            "1d",
            "2d",
            "3d"
          ],
          "appearances": 3,
          "effective_appearances": 2.85,
          "continuity": 3,
          "avg_rank": 25.3,
          "avg_rank_percentile": 50.5,
          "signal_score": 1.84,
          "avg_gain_pct": 10.14,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 以工業電腦、NVIDIA邊緣AI Box、CCTV監控與車載DVR為核心的AI視覺與影像處理解決方案",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "以工業電腦、NVIDIA邊緣AI Box、CCTV監控與車載DVR為核心的AI視覺與影像處理解決方案",
            "supply_chain_tags": [
              "工業電腦",
              "邊緣AI運算",
              "機器視覺",
              "安防與車載影像"
            ],
            "theme_hypotheses": [
              "AIoT與邊緣AI",
              "智慧製造與視覺檢測",
              "智慧交通與智慧安防"
            ],
            "rationale": "證據：官方報告列工業電腦、CCTV及車載DVR，產品頁有Jetson AI Box；推論：主軸為邊緣AI視覺方案。",
            "confidence": "high",
            "source_urls": [
              "https://www.everfocus.com/tw/upload/download_files/77e2a82332667420d65130e55f719ef0.pdf",
              "https://www.everfocus.com/tw/products-detail/EAC-10N1-N2/",
              "https://www.everfocus.com/tw/application-industries/smart_manufacturing/"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "6243",
          "name": "迅杰",
          "windows": [
            "1d",
            "20d"
          ],
          "appearances": 2,
          "effective_appearances": 1.5,
          "continuity": 1,
          "avg_rank": 24.5,
          "avg_rank_percentile": 49.6,
          "signal_score": 0.86,
          "avg_gain_pct": 13.43,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 筆電嵌入式控制器、MCU與USB-C PD控制IC，並提供巡檢、偵察、測繪等無人機系統解決方案",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "筆電嵌入式控制器、MCU與USB-C PD控制IC，並提供巡檢、偵察、測繪等無人機系統解決方案",
            "supply_chain_tags": [
              "筆電嵌入式控制器",
              "微控制器MCU",
              "USB-C PD控制IC",
              "無人機系統整合"
            ],
            "theme_hypotheses": [
              "AI無人機與邊緣運算",
              "非紅供應鏈",
              "USB-C快充"
            ],
            "rationale": "證據：官網列有EC、MCU、USB-C PD及自有無人機產品。推論：營運主題同時涵蓋PC控制晶片、快充與AI無人機系統。",
            "confidence": "high",
            "source_urls": [
              "https://www.ene.com.tw/products/114/151/",
              "https://www.ene.com.tw/products/113/153/",
              "https://www.ene.com.tw/products/uav/Inspection_Reconnaissance_Mapping/",
              "https://www.ene.com.tw/download/49/"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 14,
      "active_breadth": 2,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 14,
      "tier_change": "same"
    },
    {
      "name": "電動車 / 綠色運輸",
      "score": 9,
      "core_strength": 1.9,
      "breadth": 2,
      "provisional_count": 2,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說"
      ],
      "stocks": [
        {
          "code": "2010",
          "name": "春源",
          "windows": [
            "1d",
            "2d"
          ],
          "appearances": 2,
          "effective_appearances": 1.95,
          "continuity": 2,
          "avg_rank": 25.0,
          "avg_rank_percentile": 50.5,
          "signal_score": 1.26,
          "avg_gain_pct": 7.88,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 鋼板、特殊鋼與矽鋼材料加工，製造馬達積層鐵芯、沖壓零件、自動倉儲設備及鋼結構工程。",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "鋼板、特殊鋼與矽鋼材料加工，製造馬達積層鐵芯、沖壓零件、自動倉儲設備及鋼結構工程。",
            "supply_chain_tags": [
              "鋼板／特殊鋼加工",
              "矽鋼捲與馬達積層鐵芯",
              "汽車與家電沖壓零件",
              "自動倉儲系統"
            ],
            "theme_hypotheses": [
              "電動車與高效率馬達",
              "工業自動化與機器人",
              "智慧物流倉儲"
            ],
            "rationale": "證據：官網列示矽鋼捲、馬達積層鐵芯、沖壓零件及自動倉儲系統。推論：可對應電動車／工控馬達與物流自動化主題。",
            "confidence": "high",
            "source_urls": [
              "https://www.cysco.com.tw/product",
              "https://www.cysco.com.tw/businessdepartmentintroduction-03-page70",
              "https://www.cysco.com.tw/product-04-page78",
              "https://www.cysco.com.tw/product-05-page79"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "9921",
          "name": "巨大",
          "windows": [
            "2d",
            "20d"
          ],
          "appearances": 2,
          "effective_appearances": 1.45,
          "continuity": 1,
          "avg_rank": 19.0,
          "avg_rank_percentile": 37.5,
          "signal_score": 0.98,
          "avg_gain_pct": 17.84,
          "latest_window": "2d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 自行車整車、電動輔助自行車及高階自行車零組件",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "自行車整車、電動輔助自行車及高階自行車零組件",
            "supply_chain_tags": [
              "自行車整車製造",
              "自行車品牌通路",
              "電動輔助自行車",
              "自行車零組件"
            ],
            "theme_hypotheses": [
              "電動自行車",
              "運動健康",
              "永續移動"
            ],
            "rationale": "官方年報及公司資料證實其製造與銷售自行車、零件，經營Giant、Liv、Momentum、CADEX；電動化與永續移動為產品組合延伸推論。",
            "confidence": "high",
            "source_urls": [
              "https://www.giantgroup-cycling.com/ir-financial",
              "https://origin.giantgroup-cycling.com/files/images/iroverview/Annual%20report/Eng/114_Annual_Report_EN.pdf",
              "https://origin.giantgroup-cycling.com/news/894zmE4rJ3pW0Wy5"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 15,
      "active_breadth": 2,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 15,
      "tier_change": "same"
    },
    {
      "name": "消費電子 / 顯示器",
      "score": 8,
      "core_strength": 1.78,
      "breadth": 2,
      "provisional_count": 2,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說"
      ],
      "stocks": [
        {
          "code": "3543",
          "name": "州巧",
          "windows": [
            "2d",
            "10d"
          ],
          "appearances": 2,
          "effective_appearances": 1.6,
          "continuity": 1,
          "avg_rank": 19.5,
          "avg_rank_percentile": 38.5,
          "signal_score": 1.07,
          "avg_gain_pct": 20.23,
          "latest_window": "2d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 TFT-LCD顯示器精密沖壓件、家具金屬零組件及醫療輔具（含電動輪椅）",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "TFT-LCD顯示器精密沖壓件、家具金屬零組件及醫療輔具（含電動輪椅）",
            "supply_chain_tags": [
              "TFT-LCD零組件",
              "精密金屬沖壓",
              "家具金屬零組件",
              "醫療輔具"
            ],
            "theme_hypotheses": [
              "顯示器供應鏈",
              "居家家具與收納",
              "高齡照護與行動輔具"
            ],
            "rationale": "證據：櫃買中心產業價值鏈平台列示TFT-LCD沖壓件、家具金屬製品及醫療輔具。推論：對應顯示、居家與高齡照護終端市場。",
            "confidence": "high",
            "source_urls": [
              "https://ic.tpex.org.tw/company_list.php?stk=3543&stkName=%E5%B7%9E%E5%B7%A7&t=company_product",
              "https://wwwc.twse.com.tw/pdf/ch/3543_ch.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        },
        {
          "code": "2354",
          "name": "鴻準",
          "windows": [
            "2d",
            "3d"
          ],
          "appearances": 2,
          "effective_appearances": 1.85,
          "continuity": 2,
          "avg_rank": 30.0,
          "avg_rank_percentile": 59.5,
          "signal_score": 1.03,
          "avg_gain_pct": 10.86,
          "latest_window": "2d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 遊戲機與周邊系統組裝、金屬機構件及散熱模組製造",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "遊戲機與周邊系統組裝、金屬機構件及散熱模組製造",
            "supply_chain_tags": [
              "遊戲機ODM",
              "系統組裝",
              "金屬機構件",
              "散熱模組"
            ],
            "theme_hypotheses": [
              "遊戲主機",
              "AI伺服器與邊緣AI散熱",
              "電動車與機器人結構件"
            ],
            "rationale": "證據：公司年報列示遊戲機、散熱模組、燒結與輕金屬技術，並稱以遊戲機為基礎拓展新事業；推論：散熱及輕金屬可切入AI、車用與機器人應用。",
            "confidence": "high",
            "source_urls": [
              "https://www.foxconntech.com.tw/about/group-profile/",
              "https://www.foxconntech.com.tw/media/annual_reports/2024_2354_20250529F04_20250612_100748.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 16,
      "active_breadth": 2,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 16,
      "tier_change": "same"
    },
    {
      "name": "先進封裝 / IC 載板",
      "score": 7,
      "core_strength": 1.67,
      "breadth": 1,
      "provisional_count": 0,
      "early_cluster_count": 0,
      "mapping_basis": [
        "種子題材對照"
      ],
      "stocks": [
        {
          "code": "3189",
          "name": "景碩",
          "windows": [
            "4d",
            "5d",
            "10d"
          ],
          "appearances": 3,
          "effective_appearances": 2.3,
          "continuity": 3,
          "avg_rank": 21.7,
          "avg_rank_percentile": 42.5,
          "signal_score": 1.67,
          "avg_gain_pct": 21.09,
          "latest_window": "4d",
          "theme_basis": "種子題材對照",
          "theme_confidence": "已收錄",
          "product_label": null,
          "is_provisional": false,
          "score_factor": 1.0,
          "llm_review": {
            "product_hypothesis": "IC 載板與高階封裝基板",
            "theme_hypotheses": [
              "IC 載板",
              "先進封裝"
            ],
            "rationale": "產品可能性指向半導體封裝上游基板，與記憶體或高階運算需求可能相關。",
            "confidence": "中",
            "source_urls": [
              "https://www.kinsus.com.tw/zh-TW/Product/product",
              "https://www.kinsus.com.tw/zh-TW/Product/product/Detail/tw_sip"
            ],
            "source_status": "已取得公司官方產品資料，待人工確認是否升格 Mapping",
            "reviewed_at": "2026-08-09"
          },
          "tier": "A",
          "raw_tier": "A",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 1.0,
          "is_new": false,
          "previous_tier": "A",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 17,
      "active_breadth": 1,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 17,
      "tier_change": "same"
    },
    {
      "name": "網通 / 寬頻升級",
      "score": 7,
      "core_strength": 1.56,
      "breadth": 1,
      "provisional_count": 1,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說"
      ],
      "stocks": [
        {
          "code": "6152",
          "name": "百一",
          "windows": [
            "1d",
            "2d",
            "3d"
          ],
          "appearances": 3,
          "effective_appearances": 2.85,
          "continuity": 3,
          "avg_rank": 25.3,
          "avg_rank_percentile": 50.3,
          "signal_score": 1.84,
          "avg_gain_pct": 9.97,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 數位電視機上盒、衛星射頻通訊及家庭寬頻網通設備的OEM／ODM／JDM供應商",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "數位電視機上盒、衛星射頻通訊及家庭寬頻網通設備的OEM／ODM／JDM供應商",
            "supply_chain_tags": [
              "機上盒",
              "家庭閘道器",
              "Wi‑Fi 7／XGS-PON",
              "衛星射頻設備"
            ],
            "theme_hypotheses": [
              "家庭寬頻升級",
              "智慧家庭聯網",
              "衛星通訊"
            ],
            "rationale": "官網明列STB、LNB／多路開關、家庭網路及寬頻閘道器，並稱提供客製合作；Wi‑Fi 7與XGS-PON帶出家庭寬頻升級主題。",
            "confidence": "high",
            "source_urls": [
              "https://www.pesi.com.tw/en",
              "https://www.pesi.com.tw/en/8",
              "https://www.pesi.com.tw/en/7",
              "https://wwwc.twse.com.tw/pdf/ch/6152_ch.pdf"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 18,
      "active_breadth": 1,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 18,
      "tier_change": "same"
    },
    {
      "name": "石化 / 原物料",
      "score": 3,
      "core_strength": 0.71,
      "breadth": 1,
      "provisional_count": 1,
      "early_cluster_count": 0,
      "mapping_basis": [
        "LLM 題材假說"
      ],
      "stocks": [
        {
          "code": "6505",
          "name": "台塑化",
          "windows": [
            "1d",
            "20d"
          ],
          "appearances": 2,
          "effective_appearances": 1.5,
          "continuity": 1,
          "avg_rank": 25.5,
          "avg_rank_percentile": 51.7,
          "signal_score": 0.83,
          "avg_gain_pct": 13.28,
          "latest_window": "1d",
          "theme_basis": "LLM 題材假說",
          "theme_confidence": "high",
          "product_label": "疑似 煉製汽油、柴油、航空燃油及LPG等油品，並以輕油裂解產製乙烯、丙烯、丁二烯等石化基本原料。",
          "is_provisional": true,
          "score_factor": 0.85,
          "llm_review": {
            "product_hypothesis": "煉製汽油、柴油、航空燃油及LPG等油品，並以輕油裂解產製乙烯、丙烯、丁二烯等石化基本原料。",
            "supply_chain_tags": [
              "原油煉製",
              "成品油",
              "輕油裂解",
              "烯烴原料"
            ],
            "theme_hypotheses": [
              "石化上游原料",
              "交通與工業燃料",
              "低硫油品與減碳"
            ],
            "rationale": "證據：官方頁列油品及乙烯、丙烯、丁二烯等裂解原料，交易所列石油化工原料製造。推論：受石化循環、燃料需求與低硫減碳趨勢影響。",
            "confidence": "high",
            "source_urls": [
              "https://www.fpg.com.tw/tw/group/1",
              "https://www.twse.com.tw/pdf/ch/6505_ch.pdf",
              "https://www.fpcc.com.tw/tc/products1.php",
              "https://www.fpcc.com.tw/tc/products6.php"
            ],
            "source_status": "LLM 假說／來源待人工確認",
            "reviewed_at": "2026-08-09",
            "model": "gpt-5.6-terra"
          },
          "tier": "B",
          "raw_tier": "B",
          "is_active": true,
          "miss_streak": 0,
          "c_stagnant_days": 0,
          "base_score_factor": 0.85,
          "is_new": false,
          "previous_tier": "B",
          "tier_change": "same",
          "lifecycle_status": "持穩"
        }
      ],
      "tier": 19,
      "active_breadth": 1,
      "cooling_count": 0,
      "lifecycle": "成熟",
      "previous_tier": 19,
      "tier_change": "same"
    }
  ],
  "unmapped_candidates": [],
  "review_summary": {
    "required": 0,
    "reviewed": 0,
    "source_verified": 0
  },
  "new_trading_session": false,
  "exited_stocks": [],
  "lifecycle_summary": {
    "launching": 0,
    "expanding": 0,
    "mature": 19,
    "cooling": 0,
    "exited": 0
  }
} as const;
